# 01 Data Exploration

This notebook is used to explore the raw CSV files before loading them into PostgreSQL.

For each dataset, the structure should be:

```text
1. Read the raw CSV file
2. Preview sample records
3. Identify possible cleaning or transformation rules
```

## 1. Import libraries and define paths

This section imports the required Python libraries and defines the folder paths used to read the raw CSV files.

In [2]:
import pandas as pd

## 2. Restaurants data exploration

In [4]:
restaurants = pd.read_csv("../data/csv_files/restaurants.csv")
restaurants.head()

  restaurant_id   cuisine        city  rating
0          R001    Indian  Manchester     3.4
1          R002   Chinese       Leeds     4.1
2          R003   Chinese       Leeds     4.1
3          R004      Thai  Birmingham     3.5
4          R005  American     Bristol     4.3

## 3. Custumers_medium data exploration

In [ ]:
customers = pd.read_csv("../data/csv_files/customers_medium.csv")
customers.head()

In [5]:
doctors["specialization"].unique()

<ArrowStringArray>
['DERMATOLOGY',  'Pediatrics',  'PEDIATRICS', 'dermatology',    'Oncology',
 'Dermatology']
Length: 6, dtype: str

## 4. Appointments data exploration

In [6]:
appointments = pd.read_csv("../data/csv_files/1.ingestion/auto-ingestion/appointments01.csv")
appointments.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status
0,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled
1,A002,P032,D004,2023-06-09,2:30 pm,Therapy,No-show
2,A003,P048,D004,2023-06-28,8:00 AM,Consultation,Cancelled
3,A004,P025,D006,2023-09-01,9:15:00,Consultation,Cancelled
4,A005,P040,D003,2023-07-06,12:45:00,Emergency,No-show

## 5. Treatments data exploration

In [7]:
treatments = pd.read_csv("../data/csv_files/1.ingestion/auto-ingestion/treatments01.csv")
treatments.head()

,treatment_id,appointment_id,treatment_type,description,treatment_date
0,T001,A001,Chemotherapy,Basic screening,09/08/2023
1,T002,A002,MRI,Advanced protocol,09/06/2023
2,T003,A003,MRI,Standard procedure,28/06/2023
3,T004,A004,MRI,Basic screening,01/09/2023
4,T005,A005,ECG,Standard procedure,06/07/2023

## 6. Billing data exploration

In [8]:
billing = pd.read_csv("../data/csv_files/1.ingestion/auto-ingestion/billing01.csv")
billing.head()

,bill_id,patient_id,treatment_id,bill_date,amount,payment_method,payment_status
0,B001,P034,T001,09/08/2023,3941.97,Insurance,Pending
1,B002,P032,T002,09/06/2023,"$4,158.44",INSURANCE,Paid
2,B003,P048,T003,28/06/2023,3731.55,insurance,Paid
3,B004,P025,T004,01/09/2023,4799.86,Insurance,Failed
4,B005,P040,T005,06/07/2023,582.05,Credit Card,Pending